### ISSUE TITLE
How to vectorize decoder translation in transformer?

### ISSUE THREAD

**Issue by brando90** [azadyasar/NeuralMachineTranslation#1]
I was wondering, how does the decoder work during inference time? in particular, since the transformer takes in an entire batch (tensor) and thus outputs an entire tensor too it seemed to me that unlike an RNN, it can't take in it's own predictions without re-running the decoder every time it generates a token (e.g. it first takes in the start token then generates its first prediction then one takes its first prediction and the start token and continues). This processed didn't seem vectorized which worried me. Regardless, is this how it's done (e.g. in pytorch)?

I guess that's how it's done since your code does it:

https://github.com/azadyasar/NeuralMachineTranslation/blob/7fd9450c88d833748218c1678124cc67e3303065/src/nmt/translation/translator.py#L37

and so does the official pytorch tutorial code:

```
def evaluate(eval_model, data_source):
    eval_model.eval() # Turn on the evaluation mode
    total_loss = 0.
    src_mask = model.generate_square_subsequent_mask(bptt).to(device)
    with torch.no_grad():
        for i in range(0, data_source.size(0) - 1, bptt):
            data, targets = get_batch(data_source, i)
            if data.size(0) != bptt:
                src_mask = model.generate_square_subsequent_mask(data.size(0)).to(device)
            output = eval_model(data, src_mask)
            output_flat = output.view(-1, ntokens)
            total_loss += len(data) * criterion(output_flat, targets).item()
    return total_loss / (len(data_source) - 1)
```

https://pytorch.org/tutorials/beginner/transformer_tutorial.html

So in 2021 there is no way to vectorized this?

----

btw, thanks for sharing your awesome code and blog! :)

----

related: https://www.quora.com/unanswered/Do-transformers-use-their-own-output-during-inference-time

**Comment by brando90** [comment]
maybe this is a better example (or at least I matches your code):
```
def greedy_decode(model, src, src_mask, max_len, start_symbol):
    src = src.to(device)
    src_mask = src_mask.to(device)

    memory = model.encode(src, src_mask)
    ys = torch.ones(1, 1).fill_(start_symbol).type(torch.long).to(device)
    for i in range(max_len-1):
        memory = memory.to(device)
        memory_mask = torch.zeros(ys.shape[0], memory.shape[0]).to(device).type(torch.bool)
        tgt_mask = (generate_square_subsequent_mask(ys.size(0))
                                    .type(torch.bool)).to(device)
        out = model.decode(ys, memory, tgt_mask)
        out = out.transpose(0, 1)
        prob = model.generator(out[:, -1])
        _, next_word = torch.max(prob, dim = 1)
        next_word = next_word.item()

        ys = torch.cat([ys,
                        torch.ones(1, 1).type_as(src.data).fill_(next_word)], dim=0)
        if next_word == EOS_IDX:
          break
    return ys
```
https://pytorch.org/tutorials/beginner/translation_transformer.html

**Comment by brando90** [comment]
seems yes (found this from the nn.transformer docs link):
```
is_transformer_model = hasattr(model, 'model_type') and model.model_type == 'Transformer'if not is_transformer_model:    hidden = model.init_hidden(1)input = torch.randint(ntokens, (1, 1), dtype=torch.long).to(device)
with open(args.outf, 'w') as outf:    with torch.no_grad():  # no tracking history        for i in range(args.words):            if is_transformer_model:                output = model(input, False)                word_weights = output[-1].squeeze().div(args.temperature).exp().cpu()                word_idx = torch.multinomial(word_weights, 1)[0]                word_tensor = torch.Tensor([[word_idx]]).long().to(device)                input = torch.cat([input, word_tensor], 0)            else:                output, hidden = model(input, hidden)                word_weights = output.squeeze().div(args.temperature).exp().cpu()                word_idx = torch.multinomial(word_weights, 1)[0]                input.fill_(word_idx)
            word = corpus.dictionary.idx2word[word_idx]
            outf.write(word + ('\n' if i % 20 == 19 else ' '))
            if i % args.log_interval == 0:                print('| Generated {}/{} words'.format(i, args.words))
```
https://github.com/pytorch/examples/blob/master/word_language_model/generate.py

**Comment by brando90** [comment]
cross posted in pytorch forum: https://discuss.pytorch.org/t/is-it-possible-to-vectorize-the-inference-time-of-a-transformer-when-generating-a-new-sequence/123527

**Comment by azadyasar** [comment]
Hi @brando90 ,

First of all, thanks for the kind comment :)

> I was wondering, how does the decoder work during inference time? in particular, since the transformer takes in an entire batch (tensor) and thus outputs an entire tensor too it seemed to me that, unlike an RNN, it can't take in its own predictions without re-running the decoder every time it generates a token (e.g. it first takes in the start token then generates its first prediction then one takes its first prediction and the start token and continues). 

The generation process of the Transformer-based sequence-to-sequence models is similar to the RNN-based sequence-to-sequence models. During inference time, the model has to generate tokens one at a time while using the last generated token
as the input (auto-regressive). So evaluating a seq2seq model with teacher forcing turned off (using its own predictions rather than consuming existing tokens) is more time-consuming. Because the token at position `i` depends on the token at position `i-1` and so on.

[This function](https://github.com/azadyasar/NeuralMachineTranslation/blob/7fd9450c88d833748218c1678124cc67e3303065/src/nmt/evaluation/evaluator.py#L49) stacks data instances time-step-wise because the examples are independent of each other. But the problem is that the length of the translations can vary among data instances. Since the initial matrix has to be used throughout the generation process, we just ignore the tokens generated after the `eos` token.

If you still have some issues understanding the situation, feel free to reply :)
