### ISSUE TITLE
wrong test file specified in README

### ISSUE THREAD

**Issue by tomasohara** [azadyasar/NeuralMachineTranslation#2]
The wrong test file specified in the README:

```
    python -m nmt evaluate  --test_dataset ../data/test.csv
        =>
    python -m nmt evaluate  --test_dataset ../data/eng-tur-test.csv
``` 

This is given OK in https://towardsdatascience.com/neural-machine-translation-inner-workings-seq2seq-and-transformers-229faff5895b.

**Comment by azadyasar** [comment]
Thank you @tomasohara, will update that!
