### ISSUE TITLE
How to generate the en_sp.model file

### ISSUE THREAD

**Issue by Dylan1021** [azadyasar/NeuralMachineTranslation#3]
Could you please tell me how to generate the .model files?  And What's the en_sp.vocab meaning for?  Thanks.

**Comment by Dylan1021** [comment]
I have find out the solution. Thanks.

**Comment by Dylan1021** [comment]
However, I can't use my new .model file for training, which has a error: "RuntimeError: CUDA error: device-side assert triggered". Is there any parts I need to pay attention? Thanks.

**Comment by azadyasar** [comment]
Hi @Dylan1021,

Sorry for the late reply, I must have missed the notification. 

One possible reason of the error "RuntimeError: CUDA error: device-side assert triggered" is that the matrices being multiplied don't have matching dimensions. If you are providing either a custom dict, vocab, or model, make sure the dimensions match with the arguments you are passing during training.
